let rapportWagons=chargerRapport();
function nombreDepuisInput(id){const v=parseInt(document.getElementById(id).value,10);return Number.isFinite(v)&&v>0?v:0;}
function viderFormulaireRapport(){document.getElementById("wagonNumero").value="";document.getElementById("r240").value="0";document.getElementById("r210").value="0";document.getElementById("r170").value="0";document.getElementById("rpivot").value="0";document.getElementById("commentaire").value="";}
function ajouterWagonRapport(){const numero=document.getElementById("wagonNumero").value.trim();if(!numero){alert("Saisis le numéro du wagon.");return;}const wagon={id:Date.now(),numero,p240:nombreDepuisInput("r240"),p210:nombreDepuisInput("r210"),p170:nombreDepuisInput("r170"),pivot:nombreDepuisInput("rpivot"),commentaire:document.getElementById("commentaire").value.trim()};rapportWagons.unshift(wagon);sauvegarderRapport(rapportWagons);viderFormulaireRapport();afficherRapport();}
function supprimerWagon(id){rapportWagons=rapportWagons.filter(w=>w.id!==id);sauvegarderRapport(rapportWagons);afficherRapport();}
function calculerTotauxRapport(){return rapportWagons.reduce((t,w)=>{t.p240+=w.p240;t.p210+=w.p210;t.p170+=w.p170;t.pivot+=w.pivot;t.general+=w.p240+w.p210+w.p170+w.pivot;return t;},{p240:0,p210:0,p170:0,pivot:0,general:0});}
function afficherTotaux(){const t=calculerTotauxRapport();document.getElementById("totauxRapport").innerHTML=`<div class="row"><span>Wagons</span><span class="value">${rapportWagons.length}</span></div><div class="row"><span>240 mm</span><span class="value">${t.p240}</span></div><div class="row"><span>210 mm</span><span class="value">${t.p210}</span></div><div class="row"><span>170 mm</span><span class="value">${t.p170}</span></div><div class="row"><span>Autres / pivot</span><span class="value">${t.pivot}</span></div><div class="sep"></div><div class="row"><span>Total général</span><span class="value">${t.general}</span></div>`;}
function afficherListeWagons(){const liste=document.getElementById("listeWagons");if(rapportWagons.length===0){liste.innerHTML=`<div class="empty">Aucun wagon ajouté pour le moment.</div>`;return;}liste.innerHTML=rapportWagons.map(w=>`<article class="wagon-card"><h2><span>Wagon ${w.numero}</span><button class="delete" onclick="supprimerWagon(${w.id})">Supprimer</button></h2><div class="rows"><div class="row"><span>240 mm</span><span class="value">${w.p240}</span></div><div class="row"><span>210 mm</span><span class="value">${w.p210}</span></div><div class="row"><span>170 mm</span><span class="value">${w.p170}</span></div><div class="row"><span>Autres / pivot</span><span class="value">${w.pivot}</span></div></div>${w.commentaire?`<div class="comment">${w.commentaire}</div>`:""}</article>`).join("");}
function texteRapport(){const date=new Date().toLocaleDateString("fr-FR");const t=calculerTotauxRapport();const lignes=[`Rapport planchers - ${date}`,""];for(const w of rapportWagons.slice().reverse()){lignes.push(`Wagon ${w.numero}`,`240 mm : ${w.p240}`,`210 mm : ${w.p210}`,`170 mm : ${w.p170}`,`Autres / pivot : ${w.pivot}`);if(w.commentaire)lignes.push(`Commentaire : ${w.commentaire}`);lignes.push("");}lignes.push("Total journée",`Wagons : ${rapportWagons.length}`,`240 mm : ${t.p240}`,`210 mm : ${t.p210}`,`170 mm : ${t.p170}`,`Autres / pivot : ${t.pivot}`,`Total général : ${t.general}`);return lignes.join("\n");}
async function copierRapport(){const texte=texteRapport();try{await navigator.clipboard.writeText(texte);alert("Rapport copié.");}catch{prompt("Copie le rapport :",texte);}}
function nouvelleJournee(){if(!confirm("Effacer le rapport de la journée ?"))return;rapportWagons=[];sauvegarderRapport(rapportWagons);afficherRapport();}
function afficherRapport(){afficherTotaux();afficherListeWagons();}
